# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  libraryapp-app:
    image: libraryapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://libraryapp-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=libraryApp
      - JHIPSTER_SLEEP=10 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  libraryapp-mongodb:
    image: mongo:4.4.15
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:27017:27017
    # volumes:
    #   - ~/volumes/jhipster/libraryApp/mongodb/:/data/db/
